# Generated by Django 4.1.7 on 2023-03-10 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='linkidin_link',
            field=models.URLField(blank=True, null=True),
        ),
    ]
