# Generated by Django 3.2 on 2022-09-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220909_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='desc',
            field=models.TextField(default='', max_length=10000, verbose_name='Description'),
        ),
    ]
